# Generated by Django 6.0.4 on 2026-04-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_position', models.PositiveIntegerField(db_index=True)),
                ('keyword_score', models.FloatField(blank=True, null=True)),
                ('semantic_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='jobs.jobposting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL)),
                ('search_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to='tracking.usersearchevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersearchevent',
            index=models.Index(fields=['user', '-created_at'], name='tracking_us_user_id_7d707e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersearchevent',
            index=models.Index(fields=['-created_at'], name='tracking_us_created_1d2f91_idx'),
        ),
        migrations.AddIndex(
            model_name='jobclickevent',
            index=models.Index(fields=['user', '-created_at'], name='tracking_jo_user_id_19bf29_idx'),
        ),
        migrations.AddIndex(
            model_name='jobclickevent',
            index=models.Index(fields=['job', '-created_at'], name='tracking_jo_job_id_6362be_idx'),
        ),
        migrations.AddIndex(
            model_name='jobclickevent',
            index=models.Index(fields=['search_event', 'rank_position'], name='tracking_jo_search__9af1b2_idx'),
        ),
    ]
