# Generated by Django 6.0.4 on 2026-04-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('keyword', models.CharField(blank=True, db_index=True, max_length=255)),
                ('location_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('is_remote', models.BooleanField(blank=True, db_index=True, null=True)),
                ('employment_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='alerts_joba_user_id_7bb6c7_idx'), models.Index(fields=['user', '-created_at'], name='alerts_joba_user_id_99de6b_idx')],
            },
        ),
    ]
