# Generated by Django 6.0.4 on 2026-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
