# Generated by Django 6.0.4 on 2026-04-18 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_jobalert_filters'),
        ('jobs', '0002_rawjobrecord_normalized_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='alerts.jobalert')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_delivery_logs', to='jobs.jobposting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-sent_at'], name='alerts_aler_user_id_9d807d_idx'), models.Index(fields=['alert', '-sent_at'], name='alerts_aler_alert_i_eb5d85_idx')],
                'unique_together': {('alert', 'job')},
            },
        ),
    ]
