# Generated by Django 6.0.4 on 2026-04-18 22:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawJobRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('source_job_id', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source', 'source_job_id'], name='jobs_rawjob_source_cdc980_idx'), models.Index(fields=['source', 'fetched_at'], name='jobs_rawjob_source_388e5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('source_job_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('normalized_title', models.CharField(blank=True, db_index=True, max_length=255)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description_raw', models.TextField(blank=True)),
                ('description_clean', models.TextField(blank=True)),
                ('job_url', models.URLField(max_length=2000)),
                ('location_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('country', models.CharField(blank=True, db_index=True, max_length=120)),
                ('is_remote', models.BooleanField(db_index=True, default=False)),
                ('employment_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(blank=True, db_index=True, max_length=8)),
                ('salary_period', models.CharField(blank=True, db_index=True, max_length=32)),
                ('category_raw', models.CharField(blank=True, max_length=120)),
                ('category_normalized', models.CharField(blank=True, db_index=True, max_length=120)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('normalized_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='jobs.rawjobrecord')),
            ],
            options={
                'ordering': ['-posted_at', '-created_at'],
                'indexes': [models.Index(fields=['source', 'source_job_id'], name='jobs_jobpos_source_77a1e8_idx'), models.Index(fields=['is_remote', 'employment_type'], name='jobs_jobpos_is_remo_e44ff8_idx'), models.Index(fields=['country', 'city'], name='jobs_jobpos_country_a6d92c_idx'), models.Index(fields=['-posted_at'], name='jobs_jobpos_posted__b98875_idx')],
            },
        ),
    ]
