# Generated by Django 6.0.4 on 2026-04-18 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('vector_dimension', models.PositiveIntegerField()),
                ('embedding', models.JSONField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='jobs.jobposting')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'model_name'], name='search_jobe_provide_b24084_idx')],
                'unique_together': {('job', 'provider', 'model_name')},
            },
        ),
    ]
